### ISSUE TITLE
goofy

### ISSUE THREAD

**Issue by om3ga6400** [om3ga6400/tailwind#1]
@JarzaCode home page looks hella goofy rn

before
![image](https://github.com/user-attachments/assets/597ee13d-8899-4dd0-a002-9a2e97c04730)
after
![image](https://github.com/user-attachments/assets/77a82289-6b15-451f-93b0-0b756a85987d)

**Comment by om3ga6400** [comment]
also updates broken

**Comment by om3ga6400** [comment]
![image](https://github.com/user-attachments/assets/b9a734bb-a076-4ae3-9bee-f4163e4325c7)

**Comment by JarzaCode** [comment]
I am aware of these issues, I will not address them now
